app/assets/javascripts/snippet.js
app/assets/javascripts/soundcloud_stream.js.erb
app/assets/javascripts/soundcloud_user.js
app/assets/javascripts/track.js
app/controllers/snippets_controller.rb
app/controllers/users_controller.rb
app/views/users/show.html.erb
config/routes.rb
db/schema.rb
spec/controllers/snippets_controller_spec.rb

Pjtorps backend gets

---

app/assets/javascripts/snippet.js
app/assets/javascripts/soundcloud_stream.js.erb
app/controllers/users_controller.rb
app/views/users/show.html.erb
config/routes.rb

Snippet play

---

app/assets/stylesheets/splashpage.css.scss

adds splash page background responsivity

---

app/assets/javascripts/soundcloud_stream.js.erb
app/controllers/snippets_controller.rb

@liammccartney 
Any clue on something I can do now?

Snippet ajax response

---

app/assets/javascripts/layout.js
app/assets/stylesheets/navigation.css.scss

Completes sliding yielding div on the right side

Sliding yielding div

---

app/assets/javascripts/application.js
app/assets/javascripts/layout.js
app/assets/javascripts/soundcloud_stream.js.erb
app/assets/javascripts/soundcloud_user.js
app/controllers/facebook_controller.rb
app/controllers/pages_controller.rb
app/controllers/tracks_controller.rb
app/views/devise/soundcloud.html
app/views/layouts/application.html.erb
app/views/layouts/devise/sessions.html.erb
app/views/tracks/new.html.erb
spec/factories/follows.rb
spec/models/votes_spec.rb

@zahidkarim - implements most of steven's reccommended fixes, rms unneeded code and files, and fixes double eventing

Steven reccommended fixes

---

app/views/tracks/_track.html.erb

@zahidkarim you know what to do

adds datatags and fixes formatting

---

app/assets/javascripts/application.js
app/assets/javascripts/intialize.js.erb

moves initializing js to own file

---

app/assets/javascripts/intialize.js.erb
config/environment.rb

Intializer for sc redirect

---

app/assets/javascripts/layout.js
app/assets/stylesheets/foundation_and_overrides.scss
app/assets/stylesheets/my_profile.css.scss
app/assets/stylesheets/navigation.css.scss
app/views/tracks/_track.html.erb

@liammccartney Please merge down

Track partial layout

---

app/models/track.rb

Adds duration string track model

---

app/assets/javascripts/layout.js
app/assets/stylesheets/navigation.css.scss

Adds layers so users can click icons

---

app/models/user.rb
db/migrate/20150106192646_add_remember_created_at_to_users.rb
db/schema.rb

@chrisrcoles - take a look at this when you have a chance, it allows for a user to sign out

Add rememberable to users

---

app/assets/javascripts/soundcloud_stream.js.erb

Simplifies the next and previous button clicks

---

app/assets/stylesheets/my_profile.css.scss

@liam fixed the look of the myprofile

Fixes squished images

---

app/assets/stylesheets/player.css.scss
app/views/layouts/_player.html.erb

Widget picture positioning

---

app/assets/javascripts/follow.js
app/assets/stylesheets/splashpage.css.erb
app/controllers/follows_controller.rb
app/views/users/_follow.html.erb
app/views/users/_unfollow.html.erb
app/views/users/show.html.erb
db/schema.rb

Voting and following

---

app/assets/javascripts/soundcloud_user.js
app/controllers/tracks_controller.rb

@zahidkarim Hello Kind sir, would you be able to merge my changes?

Tracks title create

---

app/assets/javascripts/soundcloud_stream.js.erb
app/assets/stylesheets/navigation.css.scss
app/views/layouts/_player.html.erb
app/views/tracks/_track.html.erb

Image to widget

---

Gemfile
Gemfile.lock
app/controllers/snippets_controller.rb
app/helpers/facebook_helper.rb
config/initializers/devise.rb

@torpeyp - please review, oh GitMaster

Posting to facebook

---

app/assets/stylesheets/splashpage.css.erb

adds slight background to about box

---

app/assets/stylesheets/navigation.css.scss

Styles the divs to fixed and scroll

---

app/assets/javascripts/soundcloud_stream.js.erb

Adds set interval to rotate the image at a constant rate

---

app/assets/javascripts/soundcloud_user.js
app/controllers/tracks_controller.rb
app/views/tracks/create.js.erb

Ajax sc fix

---

app/views/layouts/_player.html.erb

rms lower description div

---

app/assets/javascripts/soundcloud_stream.js.erb

@liammccartney Some minor improvements on the spin.

Record spin improvements

---

app/controllers/tracks_controller.rb
app/models/snippet.rb
app/models/track.rb
app/views/tracks/show.html.erb

@liammccartney 
Please read and review. Thanks.

Tracks show view

---

app/views/tracks/show.html.erb

Snippets on tracks page

---

app/assets/stylesheets/like.css.scss
app/assets/stylesheets/my_profile.css.scss
app/assets/stylesheets/share.css.scss
app/views/snippets/_snippet.html.erb
app/views/snippets/index.html.erb
app/views/tracks/_track.html.erb
app/views/tracks/index.html.erb

Icon spacing

---

app/assets/stylesheets/my_profile.css.scss
app/views/users/show.html.erb

Fix smoushed icons

---

app/assets/javascripts/soundcloud_stream.js.erb

Delocalises track data

---

app/assets/stylesheets/navigation.css.scss
app/assets/stylesheets/player.css.scss

Widget sizing

---

app/assets/stylesheets/player.css.scss

adds tweak to art

---

app/controllers/snippets_controller.rb
app/views/snippets/index.html.erb
app/views/users/show.html.erb
config/routes.rb

Snippets on user page

---

config/environment.rb

fixes redirect to new url

---

app/assets/javascripts/soundcloud_stream.js.erb
app/controllers/snippets_controller.rb
spec/controllers/snippets_controller_spec.rb

Snippet create refactor

---

app/views/snippets/following.html.erb

Adds a page for following view

---

app/assets/javascripts/share.js
app/controllers/facebook_controller.rb
app/controllers/snippets_controller.rb
app/helpers/facebook_helper.rb
app/views/snippets/_snippet.html.erb
app/views/snippets/show.html.erb
app/views/tracks/_track.html.erb
config/routes.rb

Facebook sharing

---

app/assets/javascripts/intialize.js.erb
app/helpers/facebook_helper.rb
app/views/snippets/following.html.erb
config/application.rb
config/environment.rb

Oauth fixes

---

app/views/devise/sessions/new.html.erb
app/views/tracks/show.html.erb

Meta tag fix

---

app/assets/javascripts/soundcloud_stream.js.erb

refactors to avoid multiple event triggers

---

app/assets/stylesheets/my_profile.css.scss
app/views/users/follow_show.html.erb
app/views/users/follower_show.html.erb

@liammccartney 
Please review. Thanks.

Users profile

---

app/views/users/show.html.erb

minor line change to use show to fix follow Ajax

---

app/assets/javascripts/soundcloud_stream.js.erb
app/assets/javascripts/track.js

After proj refactor

---

app/controllers/snippets_controller.rb

share_method_fix

---

app/assets/stylesheets/my_profile.css.scss
app/views/users/show.html.erb

User profile style fix

---

README.md

@liammccartney @torpeyp updated the readme

revises README.md to reflect current state of the app
